version: 2.1

jobs:
  build:
    docker:
      # Usamos la imagen de Java 21 (la versión de tu proyecto)
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      
      # Paso 1: Correr los tests (usará tu config H2 automáticamente)
      - run:
          name: Compilar y ejecutar pruebas
          command: mvn clean test
      
      # Paso 2: Generar el .jar final
      - run:
          name: Construir archivo JAR
          command: mvn package -DskipTests
      
      # Paso 3: Guardar el archivo generado
      - store_artifacts:
          # Asegúrate de que este nombre coincida con tu artifactId en pom.xml
          path: target/recetas-saludables-0.0.1-SNAPSHOT.jar
          destination: app.jar

workflows:
  version: 2
  build_and_test:
    jobs:
      - build